name: Terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4
    - name: Configure GCP credentials
      uses: google-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ite-project-370218
    - name: Plan
      run: terraform plan
    - name: Apply
      run: terraform apply -auto-approve
